batch_size: 4
iters: 40000

train_dataset:
  type: Dataset
  dataset_root: ../../../dataset/Transfer/UAV_2_BloodCell/train
  train_path: ../../../dataset/Transfer/UAV_2_BloodCell/train/train.txt
  num_classes: 2
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: ../../../dataset/Transfer/UAV_2_BloodCell/train
  val_path: ../../../dataset/Transfer/UAV_2_BloodCell/train/val.txt
  num_classes: 2
  transforms:
    - type: Normalize
  mode: val

# optimizer:
#   type: SGD
#   momentum: 0.9
#   weight_decay: 0.0005

# lr_scheduler:
#   type: PolynomialDecay
#   learning_rate: 0.01
#   end_lr: 0
#   power: 0.9

optimizer:
  type: AdamW
  weight_decay: 0.0005
  grad_clip_cfg:
    name: ClipGradByNorm
    clip_norm: 1

lr_scheduler:
  type: MultiStepDecay
  milestones: [30000, 36000]
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5
  learning_rate: 0.0001

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

model:
  type: IceHRNet
  backbone:
    type: IceHRNetBackbone_W48
    align_corners: False
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
  num_classes: 2
  backbone_indices: [0, 1]
  aspp_ratios: [ 1, 12, 24, 36 ]
  aspp_out_channels: 256
  align_corners: False
  pretrained: Null
